# GitHub Action

# 잔디 먹는 뱀
name: Generate Snake

# 12시간마다 재생성
on:
  schedule:
      # every 12 hours
    - cron: "0 */12 * * *"

# This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    # Generates the snake
      - name: generate snake
        uses: Platane/snk/svg-only@v2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs:
            dist/github-contribution-grid-snake.svg
            dist/ocean.gif?color_snake=orange&color_dots=#DEDFE1,#7CF7FF,#94CAFE,#C38DED,#FD7EAB
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
